# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 256 # def: 256

# Directories
train_folder: /home/ml/npow1/scratch/train_hkl/_b256_b_256/
val_folder: /home/ml/npow1/scratch/train_hkl/_b256_b_256/
